apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/temp-ingress.yaml

helmGlobals:
  chartHome: ../../../charts

helmCharts:
  - name: common
    releaseName: grading-svc
    namespace: lumie-grading
    valuesFile: common-values.yaml
