{
 "title": "Falco",
 "description": "Grafana dashboard for Falco output events",
 "tags": [
  "Security",
  "Runtime"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "filter_falco_logs",
    "query": "app=\"falcosidekick\""
   },
   {
    "name": "priority",
    "label": "Priority",
    "query": {}
   },
   { "name": "top", "label": "Top", "query": "5,10,20,50" },
   { "name": "searchpattern", "label": "Search-Pattern" },
   {
    "name": "host",
    "query": "label_values({rule=~\".+\"}, hostname)"
   },
   {
    "name": "severity",
    "query": "Emergency,Alert,Critical,Error,Warning,Notice,Informational,Debug"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({rule=~\".+\", hostname=~\"$host\", priority=~\"$severity\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (source) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=~\"$severity\"}[$__range]))",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Priorities",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=~\"$severity\"}[$__range]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (rule) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=~\"$severity\"}[$__range]))",
     "legendFormat": "{{rule}}"
    }
   ]
  },
  {
   "title": "Events rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=~\"$severity\"}[1m]))",
     "legendFormat": "{{priority}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Top $top Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod) (count_over_time({app=\"falcosidekick\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Events by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (hostname) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=~\"$severity\"}[1m]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Events by Priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (priority) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=~\"$severity\"}[1m]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "🔴 Critical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Events",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "{rule=~\".+\", hostname=~\"$host\", priority=\"Critical\"} | json | line_format \"🔴 [{{.hostname}}] {{.rule}} | {{.output_fields_proc_cmdline}}\""
      }
     ]
    },
    {
     "title": "Events by Host and Source",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (hostname, source) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Critical\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Top Rules",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (rule) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Critical\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "🟠 Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Events",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "{rule=~\".+\", hostname=~\"$host\", priority=\"Error\"} | json | line_format \"🟠 [{{.hostname}}] {{.rule}} | {{.output_fields_proc_cmdline}}\""
      }
     ]
    },
    {
     "title": "Events by Host and Source",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (hostname, source) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Error\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Top Rules",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (rule) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Error\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "🟡 Warning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warning Events",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{rule=~\".+\", hostname=~\"$host\", priority=\"Warning\"} | json | line_format \"🟡 [{{.hostname}}] {{.rule}} | {{.output_fields_proc_cmdline}}\""
      }
     ]
    },
    {
     "title": "Events by Host and Source",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (hostname, source) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Warning\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Top Rules",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (rule) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Warning\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "🔵 Notice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notice Events",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "{rule=~\".+\", hostname=~\"$host\", priority=\"Notice\"} | json | line_format \"🔵 [{{.hostname}}] {{.rule}} | {{.output_fields_proc_cmdline}}\""
      }
     ]
    },
    {
     "title": "Events by Host and Source",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (hostname, source) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Notice\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Top Rules",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (rule) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Notice\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "💠 Informational",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Informational Events",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "{rule=~\".+\", hostname=~\"$host\", priority=\"Informational\"} | json | line_format \"💠 [{{.hostname}}] {{.rule}} | {{.output_fields_proc_cmdline}}\""
      }
     ]
    },
    {
     "title": "Events by Host and Source",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (hostname, source) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Informational\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Top Rules",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (rule) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Informational\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "🟣 Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Debug Events",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "{rule=~\".+\", hostname=~\"$host\", priority=\"Debug\"} | json | line_format \"🟣 [{{.hostname}}] {{.rule}} | {{.output_fields_proc_cmdline}}\""
      }
     ]
    },
    {
     "title": "Events by Host and Source",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (hostname, source) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Debug\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Top Rules",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (rule) (count_over_time({rule=~\".+\", hostname=~\"$host\", priority=\"Debug\"}[$__range]))"
      }
     ]
    }
   ]
  }
 ]
}